# Use the official Golang image to create a build artifact.
FROM golang:1.20 as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
# COPY book-ms/go.mod book-ms/go.sum ./
COPY ./book-ms .
# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the entire directory, so that the build can access the utils package

# Build the Go app with CGO disabled to produce a statically linked binary
RUN CGO_ENABLED=0 GOOS=linux go build -o book-ms .

# Start a new stage from scratch
FROM alpine:latest

# Install necessary packages
RUN apk --no-cache add ca-certificates

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/ /book-ms

# Ensure the binary has executable permissions
RUN chmod +x /book-ms

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["/book-ms/book-ms"]
